### ISSUE TITLE
Setting default image is needed.

### ISSUE THREAD

**Issue by rabiul0420** [magepeopleteam/advanced-partial-payment-or-deposit-for-woocommerce#5]
![Screenshot_13](https://github.com/magepeopleteam/advanced-partial-payment-or-deposit-for-woocommerce/assets/30313066/255afb2b-6cb7-41ea-9822-64b1fa2ba351)

![Screenshot_15](https://github.com/magepeopleteam/advanced-partial-payment-or-deposit-for-woocommerce/assets/30313066/63b2bfd7-8f95-4c06-982e-5c1aad7bc2db)

**Comment by shohan777** [comment]
The plugin is not responsible for it.
